test: add test for OPSuccinctDisputeGame (#473)
* test: add test for OPSuccinctDisputeGame

* chore: cleanup

* feat: allow custom permissioning of proposers

* wip e2e test

* update

* test: add test with real proof

* revert cycle limit

* cleanup

* cleanup

* cleanup

* nightly fmt

* remove access manager for OPSuccinctDisputeGame

* cleanup

* docs: add security note for tx.origin

* feat(contracts): add getter for L2OO

* feat: keep msg.sender usage for optimistic mode

diff --git a/crates/op-succinct/justfile b/crates/op-succinct/justfile
--- a/crates/op-succinct/justfile
+++ b/crates/op-succinct/justfile
@@ -219,6 +219,16 @@ deploy-dispute-game-factory env_file=".env":
     # Load environment variables
     source {{env_file}}
 
+    # Check if required environment variables are set.
+    if [ -z "${L2OO_ADDRESS:-}" ]; then
+        echo "Error: L2OO_ADDRESS environment variable is not set"
+        exit 1
+    fi
+    if [ -z "${PROPOSER_ADDRESSES:-}" ]; then
+        echo "Error: PROPOSER_ADDRESSES environment variable is not set"
+        exit 1
+    fi
+
     # cd into contracts directory
     cd contracts
 
@@ -231,7 +241,9 @@ deploy-dispute-game-factory env_file=".env":
     fi
     
     # Run the forge deployment script
-    L2OO_ADDRESS=$L2OO_ADDRESS forge script script/validity/OPSuccinctDGFDeployer.s.sol:OPSuccinctDFGDeployer \
+    env L2OO_ADDRESS=$L2OO_ADDRESS \
+        PROPOSER_ADDRESSES=$PROPOSER_ADDRESSES \
+        forge script script/validity/OPSuccinctDGFDeployer.s.sol:OPSuccinctDFGDeployer \
         --rpc-url $L1_RPC \
         --private-key $PRIVATE_KEY \
         --broadcast \
